sapl:
  image: interlegis/sapl25:latest
  ports:
    - "8080:8080"
  environment:
    - MYSQL_PASSWORD=saplInterlegis
    - ZEO_CLIENT=True
    - ZEO_ADDRESS=zeoserver:8100
  links:
    - mysql
    - zeoserver

zeoserver:
  image: interlegis/zeoserver:2.9.12
  volumes:
    - zeodata:/opt/zope/instances/zeo/var

mysql:
  image: mysql
  environment:
    - MYSQL_ROOT_PASSWORD=mysqlInterlegis
    - MYSQL_DATABASE=sapl
    - MYSQL_USER=sapl
    - MYSQL_PASSWORD=saplInterlegis
  volumes:
    - mysqldata:/var/lib/mysql
