FROM ubuntu:12.04
MAINTAINER "Fabio Rauber" <fabiorauber@gmail.com>

RUN apt-get install -y \
        build-essential \
        zlib1g-dev \
        libjpeg62-dev \
        libssl-dev \
        libreadline6-dev \
        libreadline6 \
        readline-common \
        libxml2-dev \
        wv \
        poppler-utils \
        libxslt1-dev \
        libfreetype6-dev \
        xpdf-utils \
        gs-common \
        catdoc \
        ppthtml \
        subversion \ 
        unzip \ 
        lynx \
        mysql-client \
        libmysqlclient-dev \
        mailutils \
        subversion 

